# ./.tmuxinator.yml

name: ROM Dynamics 
root: ~/

pre_window: export PS1=" \[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;45m\]>>>\[$(tput sgr0)\] \[$(tput sgr0)\]"

startup_window: TwistKeyboard

# USE ROM_ROBOT_MODEL as ( bobo | yoyo ) in BASHRC
windows:
  - Gazebo: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; ros2 launch romrobots_gazebo simulation.launch.py odom_tf:=True use_rviz:=True
  - Ekf: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #sleep 10; ros2 launch bobo_ekf ekf.launch.py use_sim_time:=False
  - Carto: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #sleep 13; ros2 launch bobo_carto cartographer.launch.py use_sim_time:=True
  - NAV2: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; #ros2 launch bobo_nav2 sim_navigation.launch.py map_subscribe_transient_local:=True use_sim_time:=True
  - TwistKeyboard: 
      root: ~/
      panes:
        - clear; source ~/.bashrc; rqt #ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args --remap /cmd_vel:=/cmd_vel_keyboard
